# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestExpertSearch():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testExpertSearch(self):
    self.driver.get("https://news.northwestern.edu/")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.CSS_SELECTOR, "#global-links a").click()
    self.driver.find_element(By.ID, "searchbox").click()
    self.driver.find_element(By.ID, "searchbox").send_keys("nano")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    assert self.driver.find_element(By.CSS_SELECTOR, "#results-focus > span").text == "Nano"
